### ISSUE TITLE
No plugin found

### ISSUE THREAD

**Issue by ipstas** [reywood/meteor-iron-router-scroll#1]
Hi,

I have tried it:
installed
reywood:iron-router-scroll  added, version 0.0.4

added
Router.plugin('pageScroll');
in router.js

and
'No plugin found'

Any idea what could be wrong? Latest meteor version, router installed

**Comment by reywood** [comment]
Is `Router.plugin('pageScroll')` being called on the server perhaps? Make sure it's only run on the client like so:

``` javascript
if (Meteor.isClient) {
    Router.plugin('pageScroll');
}
```

I should add that to the README.

**Comment by ipstas** [comment]
Thanks,

Yes, it was in router and router by default is shared by both client and server
